AWSTemplateFormatVersion: '2010-09-09'
Resources:
  InfraEngChallengeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: infra-eng-challenge-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: FALSE

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InfraEngChallengeBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${InfraEngChallengeBucket}/*"
